### ISSUE TITLE
Empty Games

### ISSUE THREAD

**Issue by ProjectMyst** [Rocky5/XBMC-Emustation#16]
The new update create an empty game under xbox. This is the code that is coming up, I've reverted back to the previous XBMC-Emustation and it works fine.

`	<item id="41">
		<name>4d530050</name>
		<details>[B]Released:[/B][CR] unknown [CR][B]Developer:[/B][CR] unknown[CR][B]Publisher:[/B][CR] unknown[CR][B]Genre:[/B][CR] unknown[CR][B]Players:[/B][CR] at least 1</details>
		<synopsis></synopsis>
		<thumbnail>45410042\45410079
.jpg</thumbnail>
		<mediapath>[ArtworkFolder]</mediapath>
		<onclick>RunScript( special://emustation_scripts/launcher.py,4541000d,empty,,41 )</onclick>
		<onclick>ActivateWindow(1101)</onclick>
	</item>`

**Comment by Rocky5** [comment]
None of the code for scanning Xbox games has been changed and I tested it prior to release and it worked fine. What you’re showing me there is it’s using a titleid as a name and that’s should never be the case as well it’s not coded to do that. 

I will check my game list for a broken game.

Only code changed in the create_rom_lists.py was for custom extension using files instead of making folk edit the script.

**Comment by Rocky5** [comment]
Happened to me, leave it with me.

**Comment by Rocky5** [comment]
Can you test this for me, works at my end but if you could let me know. Thanks.
[https://drive.google.com/file/d/15f1HqZcKA_TBpaOTRCHD7LE7MtjNbESN/view?usp=sharing](create_rom_lists.py)

**Comment by ProjectMyst** [comment]
Thanks for the quick reply. Yeah, It's all working on my end now :)

**Comment by Rocky5** [comment]
Cheers uploading new version to the downloader.
