### ISSUE TITLE
Demo Menu

### ISSUE THREAD

**Issue by ProjectMyst** [Rocky5/XBMC-Emustation#17]
Hi

This isn't so much as on issue but more of a request, sorry to post it here. Is there any way to add a "Demos" tab to the main menu. I have lots of demos I would like to keep, but don't want to keep them under xbox games. Having a separate menu for them would be really great. 

Maybe it could be custom menus, just like the ones that are available to add do home screen, but instead of linking it to an .xbe it would link them to a folder.

**Comment by shannonn624** [comment]
Not sure if this reply wil be sent to thread or what not but i highly agree
a demo section or a way to make multiple sections in the xbox category
would be great, or a way to create folders in each system for seperate
region games or what not, i thought the same idea about the demo
discs😁been a huge fan of rockys work since hes started working on
emustation & xbmc for gamers

**Comment by Rocky5** [comment]
I will take a look at some point, demos menu will be easy. Sub folders inside menus not so much as it’s a static list, so that would mean I would need to rethink everything I do when creating them and I can’t be arsed if I’m honest. 
(I don’t get paid to do this, and free time is scarce now-a days)
