### ISSUE TITLE
small issues and some good ideas

### ISSUE THREAD

**Issue by shannonn624** [Rocky5/XBMC-Emustation#3]
issues-
1.custom splash screen takes long time to load as well as intro video
2.custom splash screen does not show or any splash for that matter IF the intro videos enabled
3.no neogeopocket emu (neopopx v6)

ideas-
1. customize custom splash screen uptime (how long it shows as well as if it loads before or after intro video if its enabled)
2. (this ones very important on my end due to organization, and i cant figure it out myself) custom rom directories, example- nes>roms>games only, it would be nice for folders to show in the rom list (where the roms would be normally for each console) also with a media section for those folder names to have icons as well, allowing you to put something like a region flag or custom image where that image would be if it where a rom
- example- nes>roms>USA
                                  >Japan
                                  >Europe
                                  >other (custom names such as beta,prototype,unreleased, special edition, etc..)

anyways also had a few more ideas, and just wanted to say i love youre work, this is the best mod/skin ever in my opinion for xbox and id love to see more cool features such as the idea above implemented, thank you for your time

 p.s another youtube video with the full setup of art work, synopsis and game videos would be awesome as well as how to scrape those file or rename massive quantities to match names with media/synopsis (orrrrr if something such as emumovies could be implemented to scrape via console and install to user selected directory, that would be amazing)

**Comment by Rocky5** [comment]
1) Thats your Xbox, the custom splash is overlayed over the normal splash so it should show at the exact same time. As for videos haven't a clue, again could and probably is your Xbox trying to seek to the sectors containing the video file.

2) Thats by design, you get a choice. VIdeo intro or splash. I wont be changing it sorry.

3) Download it ad add it yourself :/  if there is one.

Ideas:
1) Again there is no need they splash shows for 3 seconds.

2) Not happening, you wont be in the roms folders after you transfer the roms over. So organise them on your computer ( as you already have ) and transfer them to the xbox and dont worry about it again.
( Adding subfolders increases scan times and also adds more challenges that to be honest I cant be bother with as it works how it is just now )

Thank you, I added a video to my youtube account but not sure if it was before or after this posts, I never seen this sorry.

I just released v1.1.000 with a crap load of changes so have a look there and let me know what you think.
