### ISSUE TITLE
Old Surreal64 and bad filenames

### ISSUE THREAD

**Issue by knuxyl** [Rocky5/XBMC-Emustation#48]
Surreal64 has a later version than included in latest downloader. It's version is 6.1 beta 7 r352.

Also, why did you choose to go with an arbitrary filename for the roms? Or can this recognize the rom regardless of the filename? For example,

goldeneye 007's true full romset correct filename is
`GoldenEye 007 (USA).zip`
however the .dat file is looking for
`007 goldeneye (ultrahle)720pno.zip`

If this can recognize roms regardless of filename then it's fine, however if it doesn't, I can see the use for having (ultrahle *) at the end of the filename but you should've used the n64 full romset correct filenames and have an attribute for each of which emulator to use. 

Anyways, thanks for all your work on this 👍

**Comment by Rocky5** [comment]
It's that way because N64 on the Xbox is hit or miss (more miss) I only allow the earthwormjames compilations as it's preconfigured and it's the best you're going to get. 

It's to much of a headache to allow users to just add roms as they would need to configure the emulator so they work and 99% won't and blame ES for them not confiding stuff 🤷‍♂️

I was even considering removing N64 from the supported list it's that much of a pain.  

This is also why 6.1 isn't used as the setup is different for that version and the compilation rom settings don't work with it.
