### ISSUE TITLE
URL Downloader Issues

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Rocky5/XBMC-Emustation#66]
The downloader fails with no interweb connection error. When attempting to get the download again, it asks if it should install URL Downloader.zip, I it yes and fails after attempting to handle google drive download.

**Comment by Rocky5** [comment]
Using the latest version? 

As you shouldn’t be getting no interweb connection on that version. The old Test build and 1.2 version have this issue due to the IP I used to check for a valid internet connection going down. So it broke the check.

**Comment by BiatuAutMiahn** [comment]
the version.bin in the source archive I have is `1.0.26`

**Comment by Rocky5** [comment]
Version you’re on a very old build. v1.3.019 is the latest. I would just replace your whole install with the latest version. The downloader will work then.

**Comment by Midian-AD** [comment]
John,

I'm on a very old build too getting the same error.  Can you provide
instructions on the best way to replace the installation with the newer
version? I've tried variations of instructions I found online and
suggestions from others that haven't worked worked for me. I'd like to know
what do you suggest. For example which files to download and how you would
proceed.

Also I haven't done this in a while so I was also wondering if you have
created another softmod disc like your previous one that included XBMC
emustation dashboard but with the newer version of it. Because if you do I
can use that correct my issue.

Thank you for your time and appreciate everything you've done for us.

R. "Midian" Muir

**Comment by Rocky5** [comment]
> John, I'm on a very old build too getting the same error. Can you provide instructions on the best way to replace the installation with the newer version? I've tried variations of instructions I found online and suggestions from others that haven't worked worked for me. I'd like to know what do you suggest. For example which files to download and how you would proceed. Also I haven't done this in a while so I was also wondering if you have created another softmod disc like your previous one that included XBMC emustation dashboard but with the newer version of it. Because if you do I can use that correct my issue. Thank you for your time and appreciate everything you've done for us. R. "Midian" Muir
> […](#)

V1.1.8 disc has the v1.3.000 versions so you can use that to update to later versions.

**Comment by BiatuAutMiahn** [comment]
I used the version linked in the readme of this repo. :/

**Comment by Rocky5** [comment]
> I used the prebuilt version linked in the readme of this repo. :/

Do you have googles DNS IP 8.8.8.8 blocked? as that’s what I use to check for a network connection now.

**Comment by BiatuAutMiahn** [comment]
No 8.8.8.8 is def not blocked as it's the DNS all of my devices use

**Comment by Rocky5** [comment]
> No 8.8.8.8 is def not blocked as it's the DNS all of my devices use

Hmm, only thing I can think off is try increasing the timeout for the check. 

default.py search for.
socket.setdefaulttimeout(3.0)
replace with a higher value. 

As all is working here and no one else seems to have the issue on the latest version.

**Comment by BiatuAutMiahn** [comment]
I'll test and get logs
